// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlaquakyzndujfcmstle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYXF1YWt5em5kdWpmY21zdGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDE2OTAsImV4cCI6MjA2ODk3NzY5MH0.bc3-NU8oYaS9yGsGMm8tWK3LRRDToH-wfCkfpzXPKhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});